[theme]
primaryColor = "#2563EB"
backgroundColor = "#0F141C"
secondaryBackgroundColor = "#171E2B"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
